# Site Info
title:              "The Portfolio of Liz Berberena"
description:        "Liz Berberena is a professional front-end web developer based in New Jersey. She has been coding since 2013 and graduated May 2019 from Rutgers University with a B.A. in Information Technology and Informatics."

# Author Info
author_name:        Liz Berberena
username:           lizberberena

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /projects/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
language:           en-US
favicon:            https://lizberberena.com/img/liz-pfp.jpg
logo:               https://lizberberena.com/img/liz-pfp.jpg

# Pagination Settings
paginate_path: "/pg-:num/"
paginate: 5

# Site Build
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-sitemap
  - tzinfo
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:          "posts"
    values:
      layout:        "post"

